from enum import Enum

class LoanStatus(str, Enum):
    DRAFT = "Draft"
    PENDING_APPROVAL = "Pending Approval"
    PENDING = "Pending"
    APPROVED = "Approved"
    DISBURSED = "Disbursed"
    ACTIVE = "Active"
    COMPLETED = "Completed"
    REJECTED = "Rejected"
    CANCELLED = "Cancelled"
    WRITTEN_OFF = "Written Off"
    CLOSED = "Closed"
    INTERNAL_ACCOUNT = "Internal Account"

class ClientStatus(str, Enum):
    ACTIVE = "Active"
    INACTIVE = "Inactive"
    DORMANT = "Dormant"
    CLOSED = "Closed"

class SavingsStatus(str, Enum):
    NORMAL = "Normal"
    LAPS = "LAPS"
    WITHDRAWN = "Withdrawn"

class TransactionClassification(str, Enum):
    AUTOMATIC_DEDUCTION = "AUTOMATIC_DEDUCTION"
    CUSTOMER_CASH_WITHDRAWAL = "CUSTOMER_CASH_WITHDRAWAL"
    LOAN_OFFSET = "LOAN_OFFSET"
    LAPS_TRANSFER = "LAPS_TRANSFER"
    LOAN_DISBURSEMENT = "LOAN_DISBURSEMENT"
    PROCESSING_FEE = "PROCESSING_FEE"
    PASSBOOK = "PASSBOOK"
    CONTINGENCY = "CONTINGENCY"
    MARKUP = "MARKUP"
    BANK_DEPOSIT = "BANK_DEPOSIT"
    BANK_WITHDRAWAL = "BANK_WITHDRAWAL"
    GROUP_SAVINGS_DEPOSIT = "GROUP_SAVINGS_DEPOSIT"
    GROUP_SAVINGS_WITHDRAWAL = "GROUP_SAVINGS_WITHDRAWAL"
    INDIVIDUAL_SAVINGS_DEPOSIT = "INDIVIDUAL_SAVINGS_DEPOSIT"
    INDIVIDUAL_SAVINGS_WITHDRAWAL = "INDIVIDUAL_SAVINGS_WITHDRAWAL"
    LOAN_REPAYMENT = "LOAN_REPAYMENT"
    EXCESS_PAYMENT = "EXCESS_PAYMENT"
    FULL_PAYMENT = "FULL_PAYMENT"
    OVERDUE_PAYMENT = "OVERDUE_PAYMENT"
