from typing import Protocol, TypeVar, List, Optional
T = TypeVar('T')

class Repository(Protocol[T]):
    def find_by_id(self, id: str) -> Optional[T]: ...
    def find_all(self) -> List[T]: ...
    def create(self, entity: T) -> T: ...
    def update(self, entity: T) -> T: ...
    def delete(self, id: str) -> bool: ...
