from typing import Protocol, Optional, List
from domain.entities.event_store import DomainEvent

class EventStoreRepository(Protocol):
    def append(self, event: DomainEvent) -> str: ...
    def mark_processing(self, event_id: str, processor_name: str) -> None: ...
    def mark_posted(self, event_id: str, processor_name: str) -> None: ...
    def mark_failed(self, event_id: str, processor_name: str, error_message: str) -> None: ...
    def is_processed(self, event_id: str, processor_name: str) -> bool: ...
    def get_pending_events(self) -> List[DomainEvent]: ...
