from typing import Protocol, List, Optional
from domain.entities.guarantor import Guarantor, LoanGuarantor
from interfaces.base_repository import Repository

class GuarantorRepository(Protocol):
    def find_by_id(self, guarantor_id: str) -> Optional[Guarantor]: ...
    def find_by_phone(self, phone: str) -> Optional[Guarantor]: ...
    def create_guarantor(self, guarantor: Guarantor) -> Guarantor: ...
    def link_to_loan(self, loan_guarantor: LoanGuarantor) -> LoanGuarantor: ...
    def find_for_loan(self, loan_id: str) -> List[Guarantor]: ...
    def find_links_for_loan(self, loan_id: str) -> List[LoanGuarantor]: ...
