from typing import Protocol, Optional, List
from domain.entities.ledger import FinancialTransaction, LedgerEntry

class LedgerRepository(Protocol):
    def create_transaction(self, tx: FinancialTransaction, entries: List[LedgerEntry]) -> str: ...
    def get_ledger_entries(self, branch_id: Optional[str] = None, account_code: Optional[str] = None) -> List[LedgerEntry]: ...
    def find_transaction_by_id(self, transaction_id: str) -> Optional[FinancialTransaction]: ...
    def get_transaction_entries(self, transaction_id: str) -> List[LedgerEntry]: ...
