from typing import Protocol, List, Optional
from domain.entities.loan import Loan
from domain.queries import LoanFilter
from interfaces.base_repository import Repository

class LoanRepository(Repository[Loan], Protocol):
    def find_by_client_id(self, client_id: str) -> List[Loan]: ...
    def find_active(self, filters: LoanFilter) -> List[Loan]: ...
    def approve(self, loan_id: str) -> None: ...
    def reject(self, loan_id: str) -> None: ...
    def disburse(self, loan_id: str) -> None: ...
    def create_many(self, loans: List[Loan]) -> None: ...
    def delete_by_client_id(self, client_id: str) -> bool: ...
